/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */

#include "NativeSensorsAnalyticsModule.h"

namespace rnoh {
using namespace facebook;

NativeSensorsAnalyticsModule::NativeSensorsAnalyticsModule(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(login, 1),
        ARK_METHOD_METADATA(logout, 0),
        ARK_METHOD_METADATA(profileSet, 1),
        ARK_METHOD_METADATA(profileSetOnce, 1),
        ARK_METHOD_METADATA(track, 2),
        ARK_METHOD_METADATA(trackTimerStart, 1),
        ARK_METHOD_METADATA(trackTimerEnd, 2),
        ARK_METHOD_METADATA(clearTrackTimer, 0),
        ARK_METHOD_METADATA(trackViewScreen, 2),
        ARK_METHOD_METADATA(profileIncrement, 2),
        ARK_METHOD_METADATA(profileAppend, 2),
        ARK_METHOD_METADATA(profileUnset, 1),
        ARK_METHOD_METADATA(profileDelete, 0),
        ARK_ASYNC_METHOD_METADATA(getDistinctIdPromise, 0),
        ARK_ASYNC_METHOD_METADATA(getAnonymousIdPromise, 0),
        ARK_METHOD_METADATA(registerSuperProperties, 1),
        ARK_METHOD_METADATA(unregisterSuperProperty, 1),
        ARK_METHOD_METADATA(clearSuperProperties, 0),
        ARK_METHOD_METADATA(flush, 0),
        ARK_METHOD_METADATA(deleteAll, 0),
        ARK_METHOD_METADATA(identify, 1),
        ARK_METHOD_METADATA(trackTimerPause, 1),
        ARK_METHOD_METADATA(trackTimerResume, 1),
        ARK_METHOD_METADATA(resetAnonymousId, 0),
        ARK_METHOD_METADATA(itemSet, 3),
        ARK_METHOD_METADATA(itemDelete, 2),
        ARK_ASYNC_METHOD_METADATA(getPresetPropertiesPromise, 0),
        ARK_ASYNC_METHOD_METADATA(getLoginIdPromise, 0),
        ARK_METHOD_METADATA(trackAppInstall, 1),
        ARK_METHOD_METADATA(setDynamicSuperProperties, 1),
        ARK_METHOD_METADATA(bind, 2),
        ARK_METHOD_METADATA(unbind, 2),
        ARK_METHOD_METADATA(init, 1),
        ARK_METHOD_METADATA(currentPlatform, 0),
    };
}

} // namespace rnoh
